// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _fundem_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// first_moment_survival
NumericVector first_moment_survival(NumericVector mx, NumericVector ax, NumericVector nx);
RcppExport SEXP _fundem_first_moment_survival(SEXP mxSEXP, SEXP axSEXP, SEXP nxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mx(mxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ax(axSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nx(nxSEXP);
    rcpp_result_gen = Rcpp::wrap(first_moment_survival(mx, ax, nx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fundem_rcpp_hello_world", (DL_FUNC) &_fundem_rcpp_hello_world, 0},
    {"_fundem_first_moment_survival", (DL_FUNC) &_fundem_first_moment_survival, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fundem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
